### ISSUE TITLE
need all the work completed for the sprint 2

### ISSUE THREAD

**Issue by sachindra2000** [sachindra2000/SOFTWARE-ENGINEERING-M.E.N.T#5]
please upload all the completed work to the sprint 2 file in the repository

**Comment by sachindra2000** [comment]
I have completed the use case diagram will be confirmed by tonight in the meeting.

**Comment by Nahid-os** [comment]
I have finished creating user stories. It has been published to the repository. I will define use cases by 1/03/2024 and then focus on creating class diagram.

**Comment by sachindra2000** [comment]
need to do the some updates to the diagram, planning to upload by tonight.

**Comment by sachindra2000** [comment]
upgrades are done and all have been uploaded to the GitHub.

**Comment by sachindra2000** [comment]
around 99% of the work is done at the moment. keep it up guys!! @OldManny @Nahid-os @MingmaSherpa1 @mohebulh @sachindra2000
